### PR TITLE
recipe modernization, add license file

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

Notes:
- The current build was built with `py27`, which is creating some downstream issues
- adds the license as second download
- minor fixups
- proposes @bollwyvl as maintainer

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/keepalive ready for review!

**Comment by bollwyvl** [comment]
testing this locally: due to [use of `2to3`](https://github.com/wikier/keepalive/blob/master/setup.py#L74) this probably shouldn't have been made `noarch`...

@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
the alternate approach would be to keep `noarch: python`, but set a lower bound on python, e.g. `>=3.5`

**Comment by bollwyvl** [comment]
For reference, the issue with the currently-deployed version:
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keepalive import keepalive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmphk59pf8k/lib/python3.7/site-packages/keepalive/keepalive.py", line 240
    except (socket.error, httplib.HTTPException), err:
```

**Comment by nrbgt** [comment]
@conda-forge/keepalive thoughts? going to ping gitter for a merge on this soon, probably...

**Comment by satra** [comment]
sorry missed this.

**Comment by bollwyvl** [comment]
Ah, very nice, thanks!

**Pull request merged**
